service: tag-comparison-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bucketName: tagcomparisonbucket
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    httpPort: 7000

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}

functions:
  books:
    handler: src/server.listBooks
    name: ${self:provider.stage}-${self:service}-list-books
    events:
      - http:
          path: /books
          method: get
          cors: true
  getBook:
    handler: src/server.getBook
    name: ${self:provider.stage}-${self:service}-get-book
    events:
      - http:
          path: /books/{isbn}
          method: get
          cors: true
          request:
            parameters:
              paths:
                isbn: true
  searchBooks:
    handler: src/server.searchBooks
    name: ${self:provider.stage}-${self:service}-search-books
    events:
      - http:
          path: /search
          method: get
          cors: true